### ISSUE TITLE
FNIRT output specification issues

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra-fsl#23]
@htwangtw - I was debugging failing tests and it looks like there are several field in the `FNIRT` output spec (e.g. `field_file`) that have `in_file` as the only requirements, but this is not right. 
In nipype one can specify full name by providing a string or set it to `True` in order to use the default nipype template. @effigies suggested that we don't have to support both, we could just allow for some user defined template. 

Let me know if you have thoughts about it. Don't remember if we discussed similar cases

**Comment by htwangtw** [comment]
I agree with @effigies that we should just pick one. 
I am inclined to ask for user defined template, as that would be more consistent with the docstring of FSL `FNIRT`. Tried to play around with it today but no success with fixing it.

**Comment by ghisvail** [comment]
There is no output spec for FNIRT anymore as a result of #41.

Everything is now derived from `in_file` as template for the default name in the input spec. This was necessary to get the tests green again.
