### ISSUE TITLE
Bug constructor BET

### ISSUE THREAD

**Issue by rcorredorj** [nipype/pydra-fsl#42]
Hi,

I'm just learning to use Pydra and trying to do a similar wrapper for calling elastix executables for image registration.

While checking your code, I noticed that this line should be line = line, otherwise Pydra can only have one single "BET" node in the workflow as it does not allow more than one node with the same name :
 
https://github.com/nipype/pydra-fsl/blob/8168479741e937d35d1ea02de0594a6ac5c1d565/preprocess/bet.py#L328

Cheers,

RaC

**Comment by satra** [comment]
that seems to be a very old version of the repo. the current state does not have that issue any longer: 
https://github.com/nipype/pydra-fsl/blob/30bcf28c2f77801b4a2710e1095aa7a2d49e3ef2/pydra/tasks/fsl/preprocess/bet.py#L292
